### ISSUE TITLE
Error with creating shapefile

### ISSUE THREAD

**Issue by IsiRiesi** [LCacheux68224/ProportionalCircles#4]
Hello!

I try to write my symbols into an shapefile and I get following error in the python code:

Traceback (most recent call last):
  File "C:/Users/Isi/.qgis2/python/plugins\ProportionalCircles\proportionalcirclesdialog.py", line 118, in browse
    fileName = os.path.splitext(str(fileName0))[0]+'.shp'
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 23: ordinal not in range(128)

What could be the Problem?

Thank you

Isabell

**Comment by LCacheux68224** [comment]
Hello,
Thank you for your message.
The problem is that you used a special character (in your case 'ü') either in the name of the file or the name of the directory/subdirectory where you tried to save the shapefile.
This problem should be solved in version 1.2.1 I just uploaded.
Lionel

**Comment by IsiRiesi** [comment]
Oh thank you very much.

Yes indeed, you are right..... I didn't thought of the folder name!

Now it is working!

Regards

Isabell
