### ISSUE TITLE
erreur Python à l'ouverture de Cercle proportionnel

### ISSUE THREAD

**Issue by jpinternet** [LCacheux68224/ProportionalCircles#9]
Version QGIS 2.14.6 LTR
Une erreur python apparait avant l'ouverture du formulaire du plugin cercle proportionnel lors que le projet QGIS contient une couche raster.

**Comment by LCacheux68224** [comment]
Merci pour le retour,
La modif est faite. Je teste sur les autres versions et j'envoie.

**Comment by jpinternet** [comment]
J'ai testé la correction sur la 2.14.6 LTR. C'est parfait
